package org.ofbiz.humanresext;

public enum PerfReviewStatus {
	PERF_IN_PROGRESS,PERF_SUBMITTED,PERF_REVIEW_PENDING,
	PERF_REVIEWED_BY_MGR,PERF_REVIEWED_BY_HR,PERF_REVIEW_AGREED,
	PERF_REVIEW_DISAGREE,PERF_REVIEW_COMPLETE,PERF_REVIEW_IN_PROGRESS
}
